button:
  - platform: template
    id: matrix_debug_corners
    name: "Matrix Debug Corners"
    entity_category: config
    on_press:
      - lambda: |-
          id(sunrise_active) = false;
          id(power_transition_active) = false;
          id(lamp_powered) = true;
      - light.turn_on:
          id: led_matrix
          brightness: !lambda return ((float) id(lamp_brightness_level)) / 10.0f;
          effect: "Matrix Debug Corners"
